[2025-09-16 21:36:56] ERROR: Error en la llamada a la API: HTTPSConnectionPool(host='tu-api-de-ia.com', port=443): Max retries exceeded with url: /recomendaciones (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020C2295E270>: Failed to resolve 'tu-api-de-ia.com' ([Errno 11001] getaddrinfo failed)"))
[2025-09-16 21:48:46] ERROR: Error API: HTTPSConnectionPool(host='tu-api-de-ia.com', port=443): Max retries exceeded with url: /recomendaciones (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002C846C5E120>: Failed to resolve 'tu-api-de-ia.com' ([Errno 11001] getaddrinfo failed)"))
[2025-09-17 19:37:50] ERROR: Error generando histograma: the dtypes of parameters x (object) and width (float64) are incompatible
[2025-09-17 19:37:51] ERROR: Error API: HTTPSConnectionPool(host='tu-api-de-ia.com', port=443): Max retries exceeded with url: /recomendaciones (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019AA05F41A0>: Failed to resolve 'tu-api-de-ia.com' ([Errno 11001] getaddrinfo failed)"))
[2025-09-17 19:37:51] ERROR: Error en el análisis: sequence item 0: expected str instance, tuple found
[2025-09-17 20:11:45] ERROR: Error generando histograma: the dtypes of parameters x (object) and width (float64) are incompatible
[2025-09-17 20:11:45] ERROR: Error API: HTTPSConnectionPool(host='tu-api-de-ia.com', port=443): Max retries exceeded with url: /recomendaciones (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001ABC79682F0>: Failed to resolve 'tu-api-de-ia.com' ([Errno 11001] getaddrinfo failed)"))
[2025-09-17 20:11:45] ERROR: Error en el análisis: sequence item 0: expected str instance, NoneType found
[2025-09-17 20:20:30] ERROR: Error generando histograma: the dtypes of parameters x (object) and width (float64) are incompatible
[2025-09-17 20:20:30] ERROR: Error API: HTTPSConnectionPool(host='tu-api-de-ia.com', port=443): Max retries exceeded with url: /recomendaciones (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000258DF9BB8C0>: Failed to resolve 'tu-api-de-ia.com' ([Errno 11001] getaddrinfo failed)"))
[2025-09-17 20:20:30] ERROR: Error en el análisis: sequence item 0: expected str instance, NoneType found
[2025-09-17 21:12:05] ERROR: Error API: HTTPSConnectionPool(host='tu-api-de-ia.com', port=443): Max retries exceeded with url: /recomendaciones (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F728870AD0>: Failed to resolve 'tu-api-de-ia.com' ([Errno 11001] getaddrinfo failed)"))
